name: cobrapy_to_binder
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - ca-certificates=2019.6.16
  - certifi=2019.6.16
  - cobra=0.10.1
  - fastcache=1.1.0
  - future=0.17.1
  - glpk=4.57
  - gmp=6.1.2
  - gmpy2=2.1.0b1
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcxx=8.0.0
  - libcxxabi=8.0.0
  - libffi=3.2.1
  - libgcc=4.8.5
  - libgfortran=3.0.1
  - liblapack=3.8.0
  - libopenblas=0.3.6
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.1.0
  - ncurses=6.1
  - numpy=1.16.4
  - openblas=0.3.6
  - openssl=1.1.1c
  - optlang=1.4.4
  - pandas=0.25.0
  - pcre=8.41
  - pip=19.1.1
  - python=3.6.7
  - python-dateutil=2.8.0
  - pytz=2019.1
  - readline=8.0
  - ruamel.yaml=0.14.11
  - setuptools=41.0.1
  - six=1.12.0
  - sqlite=3.29.0
  - swig=4.0.0
  - swiglpk=1.4.4
  - sympy=1.4
  - tabulate=0.8.3
  - tk=8.6.9
  - wheel=0.33.4
  - xz=5.2.4
  - zlib=1.2.11

